### ISSUE TITLE
workflow-cli panics when issuing command not supported by server API

### ISSUE THREAD

**Issue by aboyett** [deis/workflow-cli#189]
When using workflow-cli v2.4.0 against a workflow v2.3.0 cluster I encountered a `panic: runtime error: invalid memory address or nil pointer dereference` when attempting to issue commands using any of the features introduced after v2.3.0 including `deis maintenance` and `deis routing`

I would expect a response of "Feature xxx is not supported by server API vM.m.p" not a runtime error.

Here are a couple examples of the errors:

routing top-level
```
$ deis routing
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4bc0cf]

goroutine 1 [running]:
panic(0x8ef380, 0xc82000e100)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/deis/workflow-cli/cmd.DeisCmd.RoutingInfo(0x0, 0x0, 0xc8201a56b6, 0xf, 0x0, 0x0)
        /go/src/github.com/deis/workflow-cli/cmd/routing.go:23 +0x16f
github.com/deis/workflow-cli/cmd.(*DeisCmd).RoutingInfo(0xc82011f940, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:58 +0xb8
github.com/deis/workflow-cli/parser.routingInfo(0xc82011f930, 0x1, 0x1, 0x7fca49edabe0, 0xc82011f940, 0x0, 0x0)
        /go/src/github.com/deis/workflow-cli/parser/routing.go:58 +0x1e0
github.com/deis/workflow-cli/parser.Routing(0xc82011f930, 0x1, 0x1, 0x7fca49edabe0, 0xc82011f940, 0x0, 0x0)
        /go/src/github.com/deis/workflow-cli/parser/routing.go:34 +0x325
main.Command(0xc82011f930, 0x1, 0x1, 0x24)
        /go/src/github.com/deis/workflow-cli/deis.go:133 +0x1d75
main.main()
        /go/src/github.com/deis/workflow-cli/deis.go:19 +0x60
```

maintenance top-level
```
$ deis maintenance
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b504f]

goroutine 1 [running]:
panic(0x8ef380, 0xc82000e100)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/deis/workflow-cli/cmd.DeisCmd.MaintenanceInfo(0x0, 0x0, 0xc8201bb476, 0xf, 0x0, 0x0)
        /go/src/github.com/deis/workflow-cli/cmd/maintenance.go:23 +0x16f
github.com/deis/workflow-cli/cmd.(*DeisCmd).MaintenanceInfo(0xc82011f970, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:43 +0xb8
github.com/deis/workflow-cli/parser.maintenanceInfo(0xc82011f960, 0x1, 0x1, 0x7fa96a929a18, 0xc82011f970, 0x0, 0x0)
        /go/src/github.com/deis/workflow-cli/parser/maintenance.go:59 +0x1e0
github.com/deis/workflow-cli/parser.Maintenance(0xc82011f960, 0x1, 0x1, 0x7fa96a929a18, 0xc82011f970, 0x0, 0x0)
        /go/src/github.com/deis/workflow-cli/parser/maintenance.go:34 +0x325
main.Command(0xc82011f960, 0x1, 0x1, 0x24)
        /go/src/github.com/deis/workflow-cli/deis.go:135 +0x2202
main.main()
        /go/src/github.com/deis/workflow-cli/deis.go:19 +0x60
```

maintenance commands:
```
$ deis maintenance:on
Enabling maintenance mode for k8s-hello-world... Error: EOF
$ deis maintenance:off
Disabling maintenance mode for k8s-hello-world... Error: EOF
```

**Comment by Joshua-Anderson** [comment]
This is because we're not checking if the pointer [here](https://github.com/deis/workflow-cli/blob/master/cmd/maintenance.go#L21) is null before trying to read it.
