### ISSUE TITLE
Panic on `deis ps`

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#36]
I don't believe there were any running processes when I executed this command:

```console
ENG000656:k8s-claimer aaronschlesinger$ deis ps -a k8s-claimer
panic: interface conversion: interface is nil, not []interface {}

goroutine 1 [running]:
github.com/deis/workflow/client/controller/client.Client.LimitedRequest(0xc820013cb0, 0x0, 0xc82012e760, 0x4, 0x0, 0x0, 0x0, 0xc82012e767, 0x14, 0x0, ...)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/controller/client/http.go:82 +0x386
github.com/deis/workflow/client/controller/models/ps.List(0xc8200f02c0, 0x7fff5fbff9bb, 0xb, 0x64, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/controller/models/ps/ps.go:15 +0x1a7
github.com/deis/workflow/client/cmd.PsList(0x7fff5fbff9bb, 0xb, 0x64, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/cmd/ps.go:26 +0xd0
github.com/deis/workflow/client/parser.psList(0xc82000a290, 0x3, 0x3, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/parser/ps.go:67 +0x2d0
github.com/deis/workflow/client/parser.Ps(0xc82000a290, 0x3, 0x3, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/parser/ps.go:34 +0x29f
main.Command(0xc82000a290, 0x3, 0x3, 0x188850)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/deis.go:85 +0x694
main.main()
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/deis.go:18 +0x60

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by arschles** [comment]
I'm punting this to beta3

**Comment by arschles** [comment]
Client version: 

```
ENG000656:workflow-beta2 aaronschlesinger$ deis version
2.0.0-dev-32d64f9
```

**Comment by bacongobbler** [comment]
Interesting. I tried reproducing this but didn't get the same thing:

```
><> deis create
Creating Application... done, created klutzy-keepsake
Git remote deis added
remote available at ssh://git@deis.10.245.1.3.xip.io:2222/klutzy-keepsake.git
><> deis ps
=== klutzy-keepsake Processes
```

**Comment by arschles** [comment]
@bacongobbler I can't reproduce it either now. I had the same app name with no running processes, but this time on a new `deis/workflow-dev` cluster. maybe there's something that changed in the controller...

regardless, I'm going to leave this open but move to beta4. we can revisit or close in that cycle.

**Comment by bacongobbler** [comment]
closing for now. Still haven't been able to reproduce this. Let's re-open if someone does manage to reproduce the issue.
