### ISSUE TITLE
Panic on `deis apps:info` for an existing app

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#37]
The `k8s-claimer` exists and has at least one release.

```console
ENG000656:k8s-claimer aaronschlesinger$ deis apps:info -a k8s-claimer
=== k8s-claimer Application
updated:  2016-04-08T17:48:22UTC
uuid:     4220ee5b-703f-47a6-8523-d32d026d2e41
created:  2016-04-08T17:47:55UTC
url:      
owner:    arschles
id:       k8s-claimer

panic: interface conversion: interface is nil, not []interface {}

goroutine 1 [running]:
github.com/deis/workflow/client/controller/client.Client.LimitedRequest(0xc8201582d0, 0x0, 0xc82015e1a0, 0x4, 0x0, 0x0, 0x0, 0xc82015e1a7, 0x14, 0x0, ...)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/controller/client/http.go:82 +0x386
github.com/deis/workflow/client/controller/models/ps.List(0xc82018a000, 0xc8201562c0, 0xb, 0x64, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/controller/models/ps/ps.go:15 +0x1a7
github.com/deis/workflow/client/cmd.PsList(0xc8201562c0, 0xb, 0x64, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/cmd/ps.go:26 +0xd0
github.com/deis/workflow/client/cmd.AppInfo(0x7fff5fbff9ba, 0xb, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/cmd/apps.go:116 +0xa4f
github.com/deis/workflow/client/parser.appInfo(0xc82000a290, 0x3, 0x3, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/parser/apps.go:138 +0x1d7
github.com/deis/workflow/client/parser.Apps(0xc82000a290, 0x3, 0x3, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/parser/apps.go:34 +0x1ce
main.Command(0xc82000a290, 0x3, 0x3, 0x188850)
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/deis.go:87 +0xdc6
main.main()
	/Users/aaronschlesinger/gocode/src/github.com/deis/workflow/client/deis.go:18 +0x60

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by arschles** [comment]
I'm punting this to beta3

**Comment by arschles** [comment]
Client version:

```
ENG000656:workflow-beta2 aaronschlesinger$ deis version
2.0.0-dev-32d64f9
```

**Comment by arschles** [comment]
I haven't been able to reproduce this throughout the entire beta3 cycle, closing.
